name: DiscordSRV-MultiBridge
version: 1.0.0
main: com.wrs.multibridge.MultiBridge
api-version: 1.20
depend: [DiscordSRV]
author: TonyBucket (WRS Studio)
description: Addon to allow DiscordSRV to connect to multiple Discord bots and servers.
